# Generated by Django 4.1.2 on 2022-12-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='halaman',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
